### ISSUE TITLE
[feature addition] import via text

### ISSUE THREAD

**Issue by bubner** [Murray-Bridge-Bunyips/BunyipsLib_RRPathGen#1]
Turns out its really hard to know what `.splineTo(new Vector2d(-28.11, -39.51), Math.toRadians(68.20))` means without living a life of freedom units, it would be handy to integrate an import function to convert these splines to a visible path. (reverse export)

**Comment by lapadapdap** [comment]
the way you've worded this makes it sound like the description of a side quest written from the main character's perspective in their journal (quests menu)

**Comment by bubner** [comment]
A full-screen notebook shows up on the screen, i cross out the hand-written title of this issue as a checkbox ticks itself, a popup shows up and says QUEST COMPLETED +10 XP, as the issue disappears from my notebook

**Comment by bubner** [comment]
Feature not needed to be implemented due to BunyipsLib RRPathVisualizer being a thing, and since the latest changes BunyipsLib RRPathGen will use reasonable units such as field tiles and centimeters
